<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <ProjectReference Include="../../../src/backend/Tienda.Application/Tienda.Application.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../../src/backend/Tienda.Application/Tienda.Application.csproj" Link="Architecture/Tienda.Application.csproj" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
